// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	cb "github.com/m4x1202/collaborative-book"
	mock "github.com/stretchr/testify/mock"
)

// ParticipantsFactory is an autogenerated mock type for the ParticipantsFactory type
type ParticipantsFactory struct {
	mock.Mock
}

// Generate provides a mock function with given fields: numStages
func (_m *ParticipantsFactory) Generate(numStages int) (map[string]cb.Participants, error) {
	ret := _m.Called(numStages)

	var r0 map[string]cb.Participants
	if rf, ok := ret.Get(0).(func(int) map[string]cb.Participants); ok {
		r0 = rf(numStages)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]cb.Participants)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(numStages)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
