// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WSService is an autogenerated mock type for the WSService type
type WSService struct {
	mock.Mock
}

// PostToConnection provides a mock function with given fields: connectionID, data
func (_m *WSService) PostToConnection(connectionID string, data interface{}) error {
	ret := _m.Called(connectionID, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, interface{}) error); ok {
		r0 = rf(connectionID, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PostToConnections provides a mock function with given fields: connectionIDs, data
func (_m *WSService) PostToConnections(connectionIDs []string, data interface{}) error {
	ret := _m.Called(connectionIDs, data)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string, interface{}) error); ok {
		r0 = rf(connectionIDs, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
