name: Test collaborative-book-server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Go cache
      uses: actions/cache@v2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          ${{ runner.os }}-
    - name: Get dependencies
      run: go mod download
    - name: Test
      run: go test -v ./...
